name: Publish Extension
on: 
  push:
    branches:
      - main
jobs:
  publish:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Bundle Extension
        shell: bash
        run: ./bundle.sh
      - name: Publish Extension
        uses: Klemensas/chrome-extension-upload-action@1.4.1
        with:
          refresh-token: ${{ secrets.CHROME_STORE_REFRESH_TOKEN }}
          client-id: ${{ secrets.CHROME_STORE_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_STORE_CLIENT_SECRET }}
          app-id: ${{ secrets.CHROME_STORE_APP_ID }}
          file-name: './extension.zip'
          publish: true
